### ISSUE TITLE
[FEATURE]BFGMiner support

### ISSUE THREAD

**Issue by sh1ny** [prdatur/phpminer#16]
Currently, running bfgminer results in empty rigs view or even broken. Having support for it would be nice, for those of us that prefer running an actively developed miner.

**Comment by prdatur** [comment]
That is completely normal that bfgminer will produce errors. There is already a depending feature request to support multiple miner software. when I start developing this feature it, bfgminer will be part of it if the api commands are mostly the same as cgminer.

**Comment by sh1ny** [comment]
Ok, thank you. Looking forward to it.

**Comment by prdatur** [comment]
Currently bfgminer is not supported due to errors which produces the api from bfgminer. It does not return valid data. For example it recognized my GPU as a PGA. Also it seems like there is another issue that all device index are 0 which is also incorrect. With such errors phpminer will not work.

**Comment by FriedCircuits** [comment]
Maybe you can have a view only mode for BFGMiner? I use it since it is more stable for the GridSeeds. At least be able to see stats and speed? Other simple stats pages seem to work like this one
https://bitcointalk.org/index.php?topic=222632.0

I know yours is way more complex. Just a suggestion.Thanks!

**Comment by prdatur** [comment]
As you didn't read the above comment, i get invalid information back from cgminer. That means reading. So also reading is not possible. It is when i would completely build a new rpc api just for bfgminer, but this i wont.

**Comment by FriedCircuits** [comment]
I did read that. Then how home the other examples and scripts work with both cg and bfg?

**Comment by prdatur** [comment]
Sorry just have a bad day start :), The others mostly just read information and don't rely on valid data. For example the returning data if it is a gpu, pga, cpu or something else. I skip all devices which are not gpu and bfgminer just returns pga no matter which device type. There would be much changing to get it work.

**Comment by FriedCircuits** [comment]
No problem. I knows how it is. I have too many projects going on and now I am messing with this.

We'll I will see if I can get some time this weekend to mess with it. I was looking for a web solution so I can set it up and forget about and go back to what I should be working on.

Maybe I can switch back to cgminer, it's just annoying because it seems I have to replug the grid seeds when I restart cgminer but not bfgminer. But now that my settings re refined it should be okay.

**Comment by FriedCircuits** [comment]
If I switch to cgminer and the type is GSD will it pick it up?

**Comment by FriedCircuits** [comment]
Where is the code that filter\allows non GPU devices? That why I can see what it is doing and play with it.

Thanks.

**Comment by prdatur** [comment]
For example at:
https://github.com/prdatur/phpminer/blob/master/controllers/main.php
Line 1042.

But i'm currently not sure that this is the only line where it checks for gpu. You have to look by your self.

**Comment by FriedCircuits** [comment]
Thanks! I think there is stuff in the GPU.php as well.

I ended up switching to the Raspberry Pi as the controller since my computer was giving mr problems. The Raspberry Pi uses CGMiner. So now all I need to do is allow the device name ASC and hope it works. Right now with no code change the rig disappears. So it must be getting somewhere.

I also noticed I must have a different code version. Because the line on github on 1042 is on 1026 for me. Strange since I downloaded just the other day.

**Comment by rolfbartels** [comment]
Hey FriedCircuits, did you even manage to get the Gridseeds showing ? I have a 48GPU mining farm and have been testing phpminer for the past few days, I wand to include my Gridseeds but phpminer currently does not support it Would love to donate but this project seems dead ?

**Comment by FriedCircuits** [comment]
I wasn't able to get them to show. I didn't spend a lot of time on it. For my purposes I ended up using this one https://litecointalk.org/index.php?topic=4092.0
