### ISSUE TITLE
[CO-DEV] cgminer datalogger and graphs integration w/phpminer.

### ISSUE THREAD

**Issue by neurocis** [prdatur/phpminer#21]
Over the next week or so I will be working on a scheduled datalogger for cgminer which will dump on an interval all cgminer mining parameters together with configuration (for efficiency review) into a sqlite db. I want to know if there would be any possibility or what requirements phpminer would have to utilize such information.

**Comment by prdatur** [comment]
when you use sqlite, i just need the database file as an example so i can read out the tables and infos, i discovered many problems with sqlite, first the insert's are very slow and second, the database lock is ugly. there's no "give me data, i will handle the insert" it just says db locked. That's why i switched from sqlite to mysql. Maybe it is also an option for you.

**Comment by neurocis** [comment]
Actually my preference would be for mysql so I will heed your advise and go that route. Thanks!

**Comment by DanielNagy** [comment]
Are we talking about performance graphs, like what BAMT does? If so, that would be very sexy :dancer:

**Comment by neurocis** [comment]
At least the data to drive some graphs / highcharts, together with the ability to see what the configuration was at a particular performance level (ad-hoc tuning).

**Comment by neurocis** [comment]
Closing - Question answered, will share data logger once complete.
