### ISSUE TITLE
high cpu usage on rpcclient

### ISSUE THREAD

**Issue by sh1ny** [prdatur/phpminer#27]
Sometimes ( not all the time ) the rcpclient starts taking 100% cpu and slows down the cgminer/sgminer , thus reducing hashrate.

**Comment by prdatur** [comment]
How long is it at 100%?

**Comment by sh1ny** [comment]
It's really random. I can have it running fine for 24 hours, then it suddenly hits 100% and it more or less stays there until i kill it.I started running the process with php index.php on a byobu tab so i can see the output and there isn't really anything weird logged.

**Comment by prdatur** [comment]
Really strange, i thought i have fixed it, due to a missplaced low timeout value.
Which version do you use? because currently my own mining rig runs now for days without this 100% issue. Before i had it also after 1 or 2 days.

**Comment by sh1ny** [comment]
I am always on the latest git version. Kinda got ...ehh upset when you switched fro sqlite to mysql, because no upgrade from it, but it was fine. I am updating all the clients aswell.

**Comment by prdatur** [comment]
yes sorry, the reason for that was, that i used the same db class for mysql now as prev. for sqlite... As we now on mysql, this problem will be never again :). But with the high cpu usage, i have to investigate some more time. the problem is, i can't really debug because with my changes with the server socket timeout, the problem is gone for me. Hope i can fix it.

**Comment by prdatur** [comment]
Please check the latest git version if it solved the issue. I had it now also, so i decided to change the way how i create the socket server connection.

**Comment by prdatur** [comment]
If the problem occurs again, please report here.
