### ISSUE TITLE
The active pool group can not be changed

### ISSUE THREAD

**Issue by JBrace1990** [prdatur/phpminer#32]
Could we get that disabled/changed? We're able to add rigs to a pool group, but unable to then edit the group once pools are added.

**Comment by prdatur** [comment]
The error message is displayed correctly. While i can easy add pools to active group i can not change or delete pools easy, this is because the way how cgminer works with pools. once cgminer has a pool active i can not remove the active one within cgminer. also when i want to change a pool i can not do this, i can just add another one and delete the old one. So when one pool is within a group and it is the active one i would need to add the new pool, change to that pool and delete the old one. But at this point when someone has 10kh/s such change can have a duration of ~ 30 sec's because cgminer api does not allow to directly return the active pool, instead it returns the pool where the last share occured. so reading the hole thing here should make clear that this will not be possible. Sorry.
